/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * The underlying NexusVfsClient is already thread-safe (sync wrapper
 * around a background tokio thread). All public methods here are
 * synchronous and use napi `AsyncTask` wrappers to avoid blocking the
 * Node.js event loop.
 */
export declare class NexusGrpcClient {
  /**
   * Create a new gRPC client targeting the given endpoint
   * (e.g. "http://localhost:12022").
   * The TCP connection is lazy — established on first RPC call.
   */
  constructor(endpoint: string)
  /**
   * Generic gRPC call: method name + JSON payload string + auth token.
   * Returns the response as a JSON string.
   */
  call(method: string, payload: string, authToken: string): string
  /** Read a file from the VFS. Returns raw bytes. */
  read(path: string, authToken: string): Buffer
  /** Write raw bytes to a VFS path. */
  write(path: string, content: Buffer, authToken: string): void
  /** Ping the nexus gRPC server. Returns the response as a JSON string. */
  ping(authToken: string): string
}
