// This file is auto-generated by `napi build`.
// The stub below allows `require('../../native/nexus-napi')` to resolve
// before the native binary is built.

const { existsSync } = require('fs');
const { join } = require('path');

// napi-rs convention: platform-specific binary next to index.js
const candidates = [
  `nexus-napi.${process.platform}-${process.arch}.node`,
  'nexus-napi.node',
];

let nativeBinding;
for (const name of candidates) {
  const path = join(__dirname, name);
  if (existsSync(path)) {
    nativeBinding = require(path);
    break;
  }
}

if (!nativeBinding) {
  throw new Error(
    `Failed to load nexus-napi native module. Run \`bun run build:native\` first.\n` +
    `Looked for: ${candidates.join(', ')} in ${__dirname}`
  );
}

module.exports = nativeBinding;
