/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Initialize the Windows Job Object and assign the current process to it.
 *
 * Must be called once at application startup, as early as possible.
 * After this call, ALL child processes (and their children) will
 * automatically be killed when the Sudowork process exits.
 *
 * Returns true on first initialization, false if already initialized.
 * On non-Windows platforms, always returns false (no-op).
 *
 * 初始化 Windows Job Object 并将当前进程加入。
 * 必须在应用启动时尽早调用一次。
 * 调用后，所有子进程（及其子进程）会在 Sudowork 退出时自动被杀死。
 * 非 Windows 平台返回 false（空操作）。
 */
export declare function initJobObject(): boolean

/**
 * Explicitly assign a process (by PID) to the Job Object.
 *
 * This is usually not needed — child processes automatically inherit
 * job membership. Use for edge cases where a process was created
 * outside the normal spawn flow.
 *
 * 显式将进程（通过 PID）加入 Job Object。
 * 通常不需要——子进程会自动继承 Job 成员资格。
 */
export declare function assignProcessToJob(pid: number): boolean

/**
 * Check if the Job Object is active.
 * 检查 Job Object 是否已激活。
 */
export declare function isJobActive(): boolean
