/**
 * Prototype-only mock data. Phase A uses this; Phase B replaces with real API.
 * Do not import this file from any non-prototype runtime code.
 */

import type { EnterpriseMcpServerDto, EnterpriseMcpTemplateDto, EnterpriseMcpPolicyDto } from '../types';

export const MOCK_ENTERPRISE_SERVERS: EnterpriseMcpServerDto[] = [
  {
    id: 'srv-org-001',
    name: 'gitlab-mcp-cab63801',
    display_name: 'GitLab 企业仓库',
    description: '查询企业内 GitLab 仓库、提交、MR 详情。',
    icon: null,
    category: 'dev',
    scope: 'org',
    mcp_type: 'http',
    url: 'https://gitlab.internal/mcp',
    risk_level: 'low',
    bound_assistants: null,
    bound_skills: null,
    allow_read: true,
    allow_write: false,
    allow_user_disable: true,
    enabled: true,
    status: 'enabled',
    template_id: null,
    user_disabled: false,
  },
  {
    id: 'srv-org-002',
    name: 'wiki-search-7f2a',
    display_name: '企业 Wiki 检索',
    description: '检索企业内部 Wiki 知识库，支持中文模糊匹配。',
    icon: null,
    category: 'knowledge',
    scope: 'org',
    mcp_type: 'sse',
    url: 'https://wiki.internal/mcp/sse',
    risk_level: 'low',
    bound_assistants: null,
    bound_skills: null,
    allow_read: true,
    allow_write: false,
    allow_user_disable: true,
    enabled: true,
    status: 'enabled',
    template_id: null,
    user_disabled: false,
  },
  {
    id: 'srv-dept-001',
    name: 'crm-readonly-9912',
    display_name: '销售部 CRM 只读',
    description: '销售部内部 CRM 客户/订单只读访问。',
    icon: null,
    category: 'business',
    scope: 'department',
    mcp_type: 'http',
    url: 'https://crm.internal/mcp',
    risk_level: 'medium',
    bound_assistants: null,
    bound_skills: null,
    allow_read: true,
    allow_write: false,
    allow_user_disable: false,
    enabled: false,
    status: 'disabled',
    template_id: null,
    user_disabled: false,
  },
];

export const MOCK_PERSONAL_SERVERS: EnterpriseMcpServerDto[] = [
  {
    id: 'srv-user-001',
    name: 'github-mcp-3a8f1cde',
    display_name: '我的 GitHub MCP',
    description: '个人 GitHub 仓库管理与代码搜索。',
    icon: null,
    category: 'dev',
    scope: 'user',
    mcp_type: 'http',
    url: 'https://api.github.com/mcp',
    risk_level: 'low',
    bound_assistants: null,
    bound_skills: null,
    allow_read: true,
    allow_write: true,
    allow_user_disable: true,
    enabled: true,
    status: 'enabled',
    template_id: 'tpl-001',
    user_disabled: false,
  },
  {
    id: 'srv-user-002',
    name: 'jira-mine-b41e',
    display_name: 'Jira 个人视图',
    description: '我负责的 Jira 任务追踪。',
    icon: null,
    category: 'business',
    scope: 'user',
    mcp_type: 'http',
    url: 'https://jira.example.com/mcp',
    risk_level: 'low',
    bound_assistants: null,
    bound_skills: null,
    allow_read: true,
    allow_write: false,
    allow_user_disable: true,
    enabled: false,
    status: 'disabled',
    template_id: null,
    user_disabled: true,
  },
];

export const MOCK_TEMPLATES: EnterpriseMcpTemplateDto[] = [
  {
    id: 'tpl-001',
    name: 'github-mcp',
    description: 'GitHub 仓库、Issue、PR 管理（个人版）。',
    icon: null,
    category: 'dev',
    tags: ['git', 'code'],
    mcp_type: 'http',
    scope: 'org',
    risk_level: 'low',
    downloads: 128,
    rating: 4.6,
    user_config_items: [
      { name: 'GitHub Token', key: 'Authorization', required: true, description: '个人访问令牌（Personal Access Token）', target: 'headers' },
      { name: '组织名称', key: 'X-Org', required: false, description: '可选：默认组织名', target: 'headers' },
    ],
    auth_user_items: [],
    created_at: Date.now() - 1000 * 60 * 60 * 24 * 30,
    updated_at: Date.now() - 1000 * 60 * 60 * 24 * 3,
  },
  {
    id: 'tpl-002',
    name: 'slack-mcp',
    description: '阅读 Slack 消息、查询频道。',
    icon: null,
    category: 'collab',
    tags: ['chat'],
    mcp_type: 'http',
    scope: 'org',
    risk_level: 'medium',
    downloads: 76,
    rating: 4.2,
    user_config_items: [{ name: 'Slack Bot Token', key: 'Authorization', required: true, description: 'xoxb- 开头的 bot token', target: 'headers' }],
    auth_user_items: [],
    created_at: Date.now() - 1000 * 60 * 60 * 24 * 60,
    updated_at: Date.now() - 1000 * 60 * 60 * 24 * 7,
  },
  {
    id: 'tpl-003',
    name: 'weather-mcp',
    description: '免配置天气查询服务（公共示例）。',
    icon: null,
    category: 'tools',
    tags: ['demo'],
    mcp_type: 'http',
    scope: 'org',
    risk_level: 'low',
    downloads: 12,
    rating: 4.0,
    user_config_items: [],
    auth_user_items: [],
    created_at: Date.now() - 1000 * 60 * 60 * 24 * 90,
    updated_at: Date.now() - 1000 * 60 * 60 * 24 * 14,
  },
];

export const MOCK_POLICY: EnterpriseMcpPolicyDto = {
  allow_personal_mcp: true,
  allow_stdio_mcp: false,
  allow_http_sse_mcp: true,
};
